apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: database
 labels:
   "project": mgt-tool
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-dyn
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 5Gi