apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    "project": mgt-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      # https://hub.docker.com/_/mysql/
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        # resources:
        #   requests:
        #     cpu: 500m
        #     memory: 2Gi
        # env sets environment variables in the container
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: rootpw
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: password
          - name: MYSQL_DATABASE
            value: gmt
        livenessProbe:
          tcpSocket:
            port: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          subPath: data
          name: database
        - mountPath: /etc/mysql/conf.d
          name: mysql-config
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: database
      - name: mysql-config
        configMap:
           name: gmt-config-mysql