apiVersion: v1
kind: ConfigMap
metadata:
  name: gmt-config-mysql
  labels:
    "project": mgt-tool
data:
  my-custom-config.cnf: |
    [mysqld]
    bind-address = 0.0.0.0
    max_connections = 200
    character-set-server=utf8
    collation-server=utf8_bin
    default-storage-engine=INNODB
    max_allowed_packet=256M
    innodb_log_file_size=200MB