apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: laravel-pvc
 labels: "project": mgt-tool
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-dyn
spec:
 accessModes:
  - ReadWriteMany 
 resources:
   requests:
     storage: 5Gi