apiVersion: v1
kind: ConfigMap
metadata:
apiVersion: v1
kind: ConfigMap
metadata:
  name: gmt-nginx-config
  labels:
    "project": mgt-tool
data:
  gmt-nginx.conf: |
   server {
    listen 80;
    server_name _;
    root /var/www/laravel/public;
    index index.php index.html;

    access_log /var/log/nginx/gmt-access.log;
    error_log /var/log/nginx/gmt-error.log;
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ /\. {
        deny all;
    }

    location ~ \.php$ {
        try_files $uri = 404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
     }
   }