apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  labels:
     "project": mgt-tool
type: Opaque
data:
  # root password for MySQL
  # the actual password is root
  # echo -n root | base64
  rootpw: cm9vdA==
  # user for MySQL
  # the actual username is gmt
  # echo -n gmt | base64
  user: Z210
  # password for the second MySQL user
  # the actual password is gmt
  # echo -n gmt | base64
  password: Z210