apiVersion: v1
kind: Service
metadata:
  labels:
    "project": mgt-tool
  name: gmt-mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306