apiVersion: v1
kind: Service
metadata:
  labels:
    "project": mgt-tool
  name: php-web-laravel
spec:
  type: NodePort
  selector:
    app: php-laravel
  ports:
  - protocol: TCP
    nodePort: 30180
    port: 80